[project]
name = "BioOpenMCP"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.10.1",
    # Add any other dependencies here
]

[tool.setuptools.packages.find]
where = ["BioOpenMCP", "modules"]
